from __future__ import annotations

from pydantic import JsonValue

from .gate import EgressRing


def build_srt_profile(
    ring: EgressRing,
    *,
    proxy_port: int = 8788,
    agent_command: tuple[str, ...] = (),
) -> dict[str, JsonValue]:
    """Emit an Anthropic sandbox-runtime (srt) settings document for the ring.

    Zeus decides; srt enforces at the OS layer (network via its proxy with a
    per-host allowlist, filesystem via allow/deny rules). Keeping the profile
    a pure emission means Zeus carries no srt code — only its config shape.
    Wrap the agent: `srt --settings <emitted-file> -- <agent command>`.
    """
    return {
        "$comment": "generated by zeus egress ring — pair with sandbox-runtime (Apache-2.0)",
        "network": {
            "allowedDomains": sorted(ring.allowed_hosts),
            "deniedDomains": [],
            "allowLocalBinding": True,
            "httpProxyPort": proxy_port,
        },
        "filesystem": {
            "allowedWritePaths": sorted(ring.allowed_dirs),
            "deniedReadPaths": sorted(ring.blocked_dirs),
        },
        "agentCommand": list(agent_command),
    }
